(()=>{
  const launcher=document.getElementById('assistant-launcher'),panel=document.getElementById('assistant-panel'),closeButton=document.getElementById('assistant-close'),form=document.getElementById('assistant-form'),input=document.getElementById('assistant-input'),messages=document.getElementById('assistant-messages'),status=document.getElementById('assistant-status'),prompts=[...document.querySelectorAll('.assistant-prompts button')];
  let history=[],busy=false;
  const focusable=()=>[...panel.querySelectorAll('button:not(:disabled),textarea:not(:disabled)')];
  const addMessage=(content,role,error=false)=>{const item=document.createElement('div');item.className=`assistant-message assistant-message-${error?'error':role==='user'?'user':'bot'}`;item.textContent=role==='assistant'?content.replace(/\*\*/g,''):content;messages.append(item);messages.scrollTop=messages.scrollHeight};
  const setBusy=value=>{busy=value;input.disabled=value;form.querySelector('button').disabled=value;prompts.forEach(button=>button.disabled=value);status.textContent=value?'HERA is typing…':''};
  const open=()=>{panel.hidden=false;launcher.setAttribute('aria-expanded','true');launcher.setAttribute('aria-label','Close HERA Assistant');input.focus();messages.scrollTop=messages.scrollHeight};
  const close=()=>{panel.hidden=true;launcher.setAttribute('aria-expanded','false');launcher.setAttribute('aria-label','Open HERA Assistant');launcher.focus()};
  async function send(message){message=message.trim();if(!message||busy)return;const prior=history.slice(-8);addMessage(message,'user');history=[...history,{role:'user',content:message}].slice(-8);input.value='';setBusy(true);try{const response=await fetch('/api/assistant',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,history:prior})}),data=await response.json();if(!response.ok)throw new Error(data.error||`Request failed (${response.status})`);addMessage(data.reply,'assistant');history=[...history,{role:'assistant',content:data.reply}].slice(-8)}catch(error){addMessage(`Could not get a response: ${error.message}`,'assistant',true)}finally{setBusy(false);input.focus()}}
  launcher.addEventListener('click',()=>panel.hidden?open():close());closeButton.addEventListener('click',close);form.addEventListener('submit',event=>{event.preventDefault();send(input.value)});input.addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();form.requestSubmit()}});prompts.forEach(button=>button.addEventListener('click',()=>send(`Tell me about my ${button.textContent.toLowerCase()}.`)));
  document.addEventListener('keydown',event=>{if(panel.hidden)return;if(event.key==='Escape'){event.preventDefault();close()}else if(event.key==='Tab'){const items=focusable(),first=items[0],last=items.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}});
  window.addEventListener('hera:assistant-open',open);
})();
