(()=>{
'use strict';
const rootId='nutrition-root';
let date=new Date().toLocaleDateString('en-CA'),meals=[],editing=null,loading=false,photoData='';
const escape=value=>String(value??'').replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char]);
const localInput=value=>{const item=new Date(value||Date.now());item.setMinutes(item.getMinutes()-item.getTimezoneOffset());return item.toISOString().slice(0,16)};
const value=(meal,key)=>meal?.[key]??'';
function totals(){return meals.reduce((sum,meal)=>{for(const key of ['calories','proteinG','carbsG','fatG'])sum[key]=Math.round((sum[key]+(meal[key]||0))*10)/10;return sum},{calories:0,proteinG:0,carbsG:0,fatG:0})}
function card(){
 const summary=totals(),meal=meals.find(item=>item.id===editing),node=document.createElement('article');
 node.className='card full meals-card';node.dataset.mealsUi='';
 node.innerHTML=`<header class="meals-head"><div><p class="card-label">MEAL JOURNAL</p><h2>Today’s nutrition</h2><p>Log portions and macros you know. Leave unknown values blank.</p></div><button class="primary-button" type="button" data-meal-toggle>+ Add meal</button></header><div class="macro-summary" aria-label="Daily nutrition totals"><div><strong>${summary.calories}</strong><span>kcal</span></div><div><strong>${summary.proteinG}g</strong><span>Protein</span></div><div><strong>${summary.carbsG}g</strong><span>Carbs</span></div><div><strong>${summary.fatG}g</strong><span>Fat</span></div></div>${editing!==null?`<div class="meal-modal" data-meal-modal role="dialog" aria-modal="true" aria-labelledby="meal-dialog-title"><div class="meal-modal-panel">${form(meal)}</div></div>`:''}<div class="meal-list">${meals.length?meals.map(row).join(''):'<div class="meal-empty"><span>◌</span><strong>No meals logged today</strong><p>Add your first meal to build today’s nutrition summary.</p></div>'}</div><p class="meal-status" data-meal-status role="status"></p>`;
 return node;
}
function form(meal){
 const photo=meal?'':`<section class="meal-photo"><div class="meal-photo-copy"><span class="meal-photo-icon" aria-hidden="true">⌑</span><div><strong>Assess a food photo</strong><p>Choose or take a clear photo. AI creates an estimate you review before saving.</p></div></div><label class="meal-photo-button">Choose photo<input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" data-meal-photo></label><img data-meal-preview alt="Selected meal preview" hidden><button type="button" class="primary-button" data-meal-assess disabled>Assess with AI</button><p class="meal-ai-status" data-meal-ai-status role="status"></p></section>`;
 return `<form class="meal-form" data-meal-form><input type="hidden" name="id" value="${meal?.id||''}"><div class="meal-form-title"><div><span>${meal?'EDIT MEAL':'NEW MEAL'}</span><h3 id="meal-dialog-title">${meal?'Update meal details':'What did you eat?'}</h3></div><button type="button" data-meal-cancel aria-label="Close meal form">×</button></div>${photo}<div class="meal-fields"><label><span>Meal type</span><select name="mealType" required>${['breakfast','lunch','dinner','snack'].map(type=>`<option value="${type}" ${value(meal,'mealType')===type?'selected':''}>${type[0].toUpperCase()+type.slice(1)}</option>`).join('')}</select></label><label class="meal-field-wide"><span>Food or meal name</span><input name="foodName" maxlength="120" required placeholder="e.g. Chicken rice bowl" value="${escape(value(meal,'foodName'))}"></label><label><span>Date and time</span><input name="eatenAt" type="datetime-local" required max="${localInput()}" value="${localInput(meal?.eatenAt)}"></label><label><span>Portion amount</span><input name="portionAmount" type="number" min="0" max="10000" step="0.1" placeholder="1" value="${value(meal,'portionAmount')}"></label><label><span>Portion unit</span><input name="portionUnit" maxlength="30" placeholder="serving, g, cup" value="${escape(value(meal,'portionUnit'))}"></label><fieldset class="meal-macros meal-field-full"><legend>Nutrition information <small>optional</small></legend>${[['calories','Calories','kcal',10000],['proteinG','Protein','g',1000],['carbsG','Carbohydrates','g',2000],['fatG','Fat','g',1000]].map(([name,label,unit,max])=>`<label><span>${label}</span><div><input name="${name}" type="number" min="0" max="${max}" step="0.1" placeholder="—" value="${value(meal,name)}"><i>${unit}</i></div></label>`).join('')}</fieldset><label class="meal-field-full"><span>Notes <small>optional</small></span><textarea name="notes" maxlength="500" rows="2" placeholder="Ingredients or preparation details">${escape(value(meal,'notes'))}</textarea></label></div><div class="meal-form-actions"><button class="primary-button" type="submit">${meal?'Save changes':'Save meal'}</button><button type="button" data-meal-cancel>Cancel</button></div></form>`;
}
function row(meal){const time=new Date(meal.eatenAt).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}),portion=meal.portionAmount!==null?`${meal.portionAmount} ${escape(meal.portionUnit||'serving')}`:'Portion not entered',macro=[meal.calories!==null?`${meal.calories} kcal`:null,meal.proteinG!==null?`P ${meal.proteinG}g`:null,meal.carbsG!==null?`C ${meal.carbsG}g`:null,meal.fatG!==null?`F ${meal.fatG}g`:null].filter(Boolean).join(' · ');return `<section class="meal-row"><div class="meal-icon" aria-hidden="true">${{breakfast:'☀',lunch:'◐',dinner:'☾',snack:'✦'}[meal.mealType]}</div><div class="meal-copy"><span>${escape(meal.mealType)} · ${time}</span><h3>${escape(meal.foodName)}</h3><p>${portion}${macro?` · ${macro}`:''}</p></div><div class="meal-actions"><button type="button" data-meal-edit="${meal.id}">Edit</button><button type="button" data-meal-delete="${meal.id}" aria-label="Delete ${escape(meal.foodName)}">Delete</button></div></section>`}
function mount(){const root=document.getElementById(rootId);if(!root||root.querySelector('[data-meals-ui]')||!root.querySelector('.nutrition-grid'))return;root.querySelector('.nutrition-grid').prepend(card())}
function rerender(){document.querySelector('[data-meals-ui]')?.replaceWith(card());document.body.classList.toggle('modal-open',editing!==null)}
function close(){editing=null;photoData='';rerender()}
async function load(){if(loading)return;loading=true;try{const response=await fetch(`/api/meals?date=${date}`,{cache:'no-store'}),data=await response.json();if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);meals=data.meals||[];mount()}catch(error){console.error('Meal journal unavailable:',error)}finally{loading=false}}
async function assess(button){const form=button.closest('form'),status=form.querySelector('[data-meal-ai-status]');if(!photoData)return;button.disabled=true;status.textContent='AI is assessing visible foods and portions…';try{const response=await fetch('/api/meals/assess-image',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image:photoData})}),result=await response.json();if(!response.ok)throw new Error(result.error||`HTTP ${response.status}`);for(const key of ['foodName','portionAmount','portionUnit','calories','proteinG','carbsG','fatG','notes'])if(result.draft[key]!==null&&result.draft[key]!==undefined)form.elements[key].value=result.draft[key];status.textContent=`${result.disclaimer} Confidence: ${result.draft.confidence}.`}catch(error){status.textContent=`Could not assess photo: ${error.message}`}finally{button.disabled=false}}
async function save(form){const status=form.querySelector('[data-meal-ai-status]')||form.closest('[data-meals-ui]').querySelector('[data-meal-status]'),data=Object.fromEntries(new FormData(form)),id=data.id;delete data.id;for(const key of ['portionAmount','calories','proteinG','carbsG','fatG'])data[key]=data[key]===''?null:Number(data[key]);data.eatenAt=new Date(data.eatenAt).toISOString();form.querySelectorAll('button,input,select,textarea').forEach(control=>control.disabled=true);status.textContent='Saving meal…';try{const response=await fetch(id?`/api/meals/${id}`:'/api/meals',{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),result=await response.json();if(!response.ok)throw new Error(result.error||`HTTP ${response.status}`);editing=null;photoData='';document.body.classList.remove('modal-open');await reload()}catch(error){status.textContent=`Could not save: ${error.message}`;form.querySelectorAll('button,input,select,textarea').forEach(control=>control.disabled=false)}}
async function remove(id){const meal=meals.find(item=>item.id===id);if(!meal||!confirm(`Delete “${meal.foodName}”?`))return;const response=await fetch(`/api/meals/${id}`,{method:'DELETE'});if(!response.ok){const result=await response.json().catch(()=>({}));alert(result.error||'Could not delete meal');return}await reload()}
async function reload(){const response=await fetch(`/api/meals?date=${date}`,{cache:'no-store'}),data=await response.json();if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);meals=data.meals||[];rerender()}
document.addEventListener('change',event=>{if(!event.target.matches('[data-meal-photo]'))return;const file=event.target.files[0],status=event.target.closest('form').querySelector('[data-meal-ai-status]'),button=event.target.closest('form').querySelector('[data-meal-assess]'),preview=event.target.closest('form').querySelector('[data-meal-preview]');if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>3*1024*1024){status.textContent='Choose a JPEG, PNG, or WebP image smaller than 3 MB.';event.target.value='';return}const reader=new FileReader();reader.onload=()=>{photoData=reader.result;preview.src=photoData;preview.hidden=false;button.disabled=false;status.textContent='Photo ready. It is not saved by HERA.'};reader.readAsDataURL(file)});
document.addEventListener('click',event=>{if(event.target.matches('[data-meal-modal]'))return close();const button=event.target.closest('[data-meal-toggle],[data-meal-cancel],[data-meal-edit],[data-meal-delete],[data-meal-assess]');if(!button)return;if(button.matches('[data-meal-assess]'))return assess(button);if(button.matches('[data-meal-delete]'))return remove(Number(button.dataset.mealDelete));if(button.matches('[data-meal-toggle]'))editing=0;else if(button.matches('[data-meal-edit]'))editing=Number(button.dataset.mealEdit);else return close();photoData='';rerender();document.querySelector('[data-meal-form] input[name="foodName"]')?.focus()});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&editing!==null)close()});
document.addEventListener('submit',event=>{if(event.target.matches('[data-meal-form]')){event.preventDefault();save(event.target)}});
new MutationObserver(()=>{mount();if(document.getElementById(rootId)&&!meals.length)load()}).observe(document.getElementById('page-content'),{childList:true,subtree:true});
load();
})();
