(()=>{
  const profileKey='hera.profile',preferencesKey='hera.notification.preferences',historyKey='hera.notifications.history';
  const defaults={name:'HERA User',pronouns:'',birthYear:'',units:'metric'},preferenceDefaults={cycle:true,symptoms:true,wearable:true,signals:true};
  const read=(key,fallback)=>{try{return {...fallback,...JSON.parse(localStorage.getItem(key)||'{}')}}catch{return {...fallback}}};
  const escape=value=>String(value??'').replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char]);
  function markup(){const profile=read(profileKey,defaults),preferences=read(preferencesKey,preferenceDefaults),history=(()=>{try{return JSON.parse(localStorage.getItem(historyKey)||'[]')}catch{return[]}})();return `<div class="profile-grid">
    <article class="card profile-card full"><p class="card-label">PERSONAL DETAILS</p><h2>Your HERA space</h2><p class="muted">Prototype settings remain in this browser. Avoid entering sensitive medical details.</p><form class="profile-form" id="profile-form"><label>Display name<input name="name" maxlength="50" value="${escape(profile.name)}" required></label><label>Pronouns<input name="pronouns" maxlength="30" value="${escape(profile.pronouns)}" placeholder="Optional"></label><label>Birth year<input name="birthYear" type="number" min="1900" max="${new Date().getFullYear()}" value="${escape(profile.birthYear)}" placeholder="Optional"></label><label>Units<select name="units"><option value="metric" ${profile.units==='metric'?'selected':''}>Metric · °C</option><option value="imperial" ${profile.units==='imperial'?'selected':''}>Imperial · °F</option></select></label><button class="primary-button profile-save" type="submit">Save locally</button><p class="muted" id="profile-status" role="status"></p></form><p class="profile-local-note">Stored only in this browser; not an authenticated account.</p></article>
    <article class="card profile-card"><p class="card-label">NOTIFICATIONS</p><h2>Awareness preferences</h2><div class="profile-switches">${[['cycle','Cycle updates','Cycle day and interval changes'],['symptoms','Symptom patterns','Repeated self-reported symptoms'],['wearable','Wearable status','Connection and wear status'],['signals','Signal changes','Sudden wearable reading changes']].map(([key,title,detail])=>`<label class="profile-switch"><span>${title}<small>${detail}</small></span><input type="checkbox" data-notification-preference="${key}" ${preferences[key]?'checked':''}></label>`).join('')}</div></article>
    <article class="card profile-card"><p class="card-label">CONNECTED DEVICE</p><h2>HERA wearable</h2><div class="data-list"><div class="data-row"><span>Device</span><strong data-reading="deviceId">--</strong></div><div class="data-row"><span>Status</span><strong data-reading="wearing">--</strong></div><div class="data-row"><span>Last reading</span><strong data-reading="receivedAt">--</strong></div></div></article>
    <article class="card profile-card full"><p class="card-label">ALERT HISTORY</p><h2>Recent awareness notices</h2><div class="profile-alert-history">${history.length?history.slice(0,10).map(item=>`<article class="notification-item"><span class="notification-icon">${escape(item.icon)}</span><div><strong>${escape(item.title)}</strong><p>${escape(item.body)}</p><time>${escape(item.time)}</time></div></article>`).join(''):'<p class="muted">No pattern or signal alerts recorded yet.</p>'}</div></article>
    <article class="card profile-card"><p class="card-label">PRIVACY & EXPORT</p><h2>Your prototype data</h2><p>Download stored check-ins, cycles, and wearable readings as JSON.</p><div class="profile-actions"><button class="primary-button" id="profile-export" type="button">Export HERA data</button></div><p class="profile-local-note">Export may contain sensitive wellness data. Store it securely.</p></article>
    <article class="card profile-card danger-zone"><p class="card-label">DATA DELETION</p><h2>Account deletion unavailable</h2><p>No authenticated account or safe all-data deletion endpoint exists yet. Browser-only profile settings can be cleared.</p><div class="profile-actions"><button class="text-button" id="profile-clear-local" type="button">Clear local profile</button><button type="button" disabled>Delete server data</button></div></article>
  </div>`}
  function render(){const root=document.getElementById('profile-root');if(!root||root.dataset.ready)return;root.dataset.ready='true';root.innerHTML=markup();window.dispatchEvent(new Event('hera:profile-rendered'))}
  document.addEventListener('submit',event=>{if(event.target.id!=='profile-form')return;event.preventDefault();const data=Object.fromEntries(new FormData(event.target));localStorage.setItem(profileKey,JSON.stringify(data));document.getElementById('profile-status').textContent='Saved in this browser.'});
  document.addEventListener('change',event=>{const key=event.target.dataset.notificationPreference;if(!key)return;const preferences=read(preferencesKey,preferenceDefaults);preferences[key]=event.target.checked;localStorage.setItem(preferencesKey,JSON.stringify(preferences));window.dispatchEvent(new Event('hera:notifications-refresh'))});
  document.addEventListener('click',async event=>{if(event.target.id==='profile-clear-local'){localStorage.removeItem(profileKey);document.getElementById('profile-root').dataset.ready='';render()}if(event.target.id==='profile-export'){event.target.disabled=true;try{const responses=await Promise.all(['/api/checkins/1?limit=100','/api/cycles/1?limit=100','/api/wearable/history?limit=100'].map(url=>fetch(url,{cache:'no-store'})));if(responses.some(response=>!response.ok))throw new Error('Could not retrieve all records');const [checkins,cycles,wearable]=await Promise.all(responses.map(response=>response.json())),blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),checkins,cycles,wearable},null,2)],{type:'application/json'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`hera-export-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(link.href)}catch(error){alert(error.message)}finally{event.target.disabled=false}}});
  new MutationObserver(render).observe(document.getElementById('page-content'),{childList:true});render();
})();
