(()=>{
const root=()=>document.getElementById('sleep-root');
const escape=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const fields=[['sleepQuality','Sleep quality'],['morningRestedness','Morning restedness'],['sleepOnsetDifficulty','Falling-asleep difficulty'],['sleepDisturbances','Sleep disturbances'],['morningSleepiness','Morning sleepiness'],['scheduleConsistency','Schedule consistency']];
const date=value=>new Date(`${value}T00:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});
function showSleepSaved(record){const previousFocus=document.activeElement,dialog=document.createElement('dialog');dialog.className='sleep-save-confirmation';dialog.setAttribute('aria-labelledby','sleep-save-title');dialog.innerHTML=`<div class="sleep-save-icon" aria-hidden="true">✓</div><p class="card-label">SLEEP LOG SAVED</p><h2 id="sleep-save-title">Your night is recorded</h2><p>Your sleep details for <strong>${date(record.date)}</strong> were saved and your sleep insights are now up to date.</p>${record.sleepWellnessScore!=null?`<div class="sleep-save-score"><span>Sleep wellness score</span><strong>${Math.round(record.sleepWellnessScore)}%</strong></div>`:''}<button class="primary-button" type="button">Done</button>`;document.body.appendChild(dialog);const close=()=>{dialog.close();dialog.remove();previousFocus?.focus()};dialog.querySelector('button').addEventListener('click',close);dialog.addEventListener('cancel',event=>{event.preventDefault();close()});dialog.addEventListener('click',event=>{if(event.target===dialog)close()});dialog.showModal();dialog.querySelector('button').focus()}
const duration=record=>{if(!record.estimatedSleepTime||!record.wakeTime)return '—';const minutes=value=>Number(value.slice(0,2))*60+Number(value.slice(3));const total=(minutes(record.wakeTime)-minutes(record.estimatedSleepTime)+1440)%1440;return `${Math.floor(total/60)}h ${total%60}m`};
function markup(records){const latest=records[0];return `<section class="sleep-hero card"><div><p class="card-label">SLEEP WELLNESS</p><h2>${latest?.sws.score??'—'}<small>/100</small></h2><p>${latest?.sws.score==null?'Complete tonight’s sleep log to calculate your score.':'Latest self-reported Sleep Wellness Score.'}</p></div><div class="sleep-hero-meta"><strong>${latest?duration(latest):'—'}</strong><span>estimated sleep</span></div></section><section class="sleep-grid"><form class="card sleep-form" id="sleep-form"><div><p class="card-label">NIGHTLY LOG</p><h2>How did you sleep?</h2></div><label>Date<input name="date" type="date" required max="${new Date().toISOString().slice(0,10)}"></label><div class="sleep-times"><label>Bedtime<input name="bedtime" type="time" value="22:30" required></label><label>Fell asleep<input name="estimatedSleepTime" type="time" value="23:00" required></label><label>Wake time<input name="wakeTime" type="time" value="07:00" required></label></div>${fields.map(([name,label])=>`<label>${label}<span class="sleep-scale"><input name="${name}" type="range" min="1" max="5" value="3" required><output>3</output></span></label>`).join('')}<label>Nighttime awakenings<input name="nighttimeAwakenings" type="number" min="0" max="20" value="0" required></label><label>Notes<textarea name="notes" maxlength="1000" placeholder="Optional context"></textarea></label><button class="primary-button" type="submit">Save sleep log</button><p id="sleep-status" role="status"></p></form><article class="card"><p class="card-label">RECENT SLEEP</p><div class="sleep-history">${records.length?records.map(item=>`<div><span><strong>${date(item.date)}</strong><small>${duration(item)} · Quality ${item.sleepQuality??'—'}/5</small></span><b>${item.sws.score??'—'}</b></div>`).join(''):'<p class="muted">No sleep logs yet.</p>'}</div><p class="sleep-disclaimer">Self-reported wellness summary only. Not diagnosis or clinical sleep measurement.</p></article></section>`}
async function load(){const host=root();if(!host)return;try{const response=await fetch('/api/sleep/1?limit=30');if(!response.ok)throw new Error('Could not load sleep records');const data=await response.json();host.innerHTML=markup(data.records);const records=data.records,latest=records[0],scored=records.filter(record=>record.sws?.score!=null),average=scored.length?Math.round(scored.reduce((sum,record)=>sum+record.sws.score,0)/scored.length):'—',summary=document.createElement('div');summary.className='sleep-summary';summary.setAttribute('aria-label','Sleep overview');summary.innerHTML=`<article><span class="sleep-summary-icon" aria-hidden="true">☾</span><div><small>Latest duration</small><strong>${latest?duration(latest):'—'}</strong></div></article><article><span class="sleep-summary-icon" aria-hidden="true">◇</span><div><small>Recent average</small><strong>${average}${average==='—'?'':'/100'}</strong></div></article><article><span class="sleep-summary-icon" aria-hidden="true">✓</span><div><small>Logs recorded</small><strong>${records.length}</strong></div></article>`;host.querySelector('.sleep-hero').after(summary);wire()}catch(error){host.innerHTML=`<div class="card nutrition-error">${escape(error.message)}</div>`}}
function wire(){const form=document.getElementById('sleep-form');if(!form)return;form.date.value=new Date().toISOString().slice(0,10);form.querySelectorAll('input[type="range"]').forEach(input=>input.addEventListener('input',()=>input.nextElementSibling.value=input.value));form.addEventListener('submit',async event=>{event.preventDefault();const status=document.getElementById('sleep-status'),data=Object.fromEntries(new FormData(form));['sleepQuality','morningRestedness','sleepOnsetDifficulty','sleepDisturbances','morningSleepiness','scheduleConsistency','nighttimeAwakenings'].forEach(name=>data[name]=Number(data[name]));status.textContent='Saving…';try{const response=await fetch('/api/sleep/1',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),result=await response.json();if(!response.ok)throw new Error(result.error||'Could not save sleep log');await load();showSleepSaved({...result.record,sleepWellnessScore:result.sws?.score})}catch(error){status.textContent=error.message}})}
window.addEventListener('hera:page-rendered',load);
load();
})();
